swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /account/transactions/{accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get last transactions
      description: API for fetching transactions of last month
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: accountId
          in: path
          description: ID of account that needs to be fetched
          required: true
          type: string
        - name: monthSelected
          in: query
          description: Number of the chosen month
          required: false
          type: integer
          enum:
            - 1 => 12
      produces:
        - application/json
      responses:
        "200":
          description: Account with transactions retrieved successully
          schema:
            $ref: "#/definitions/AccountTransactions"
        "401":
          description: Unauthorized
        "400":
          description: Invalid Fields
        "404":
          description: Account not found
        "500":
          description: Internal Server Error
  /account/transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Transaction informations
      description: API for fetching a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of transaction that needs to be fetched
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transactions retrieved successully
          schema:
            $ref: "#/definitions/TransactionObject"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction information
      description: API for updating informations in a transaction
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of transaction to update
          required: true
          type: string
        - in: body
          name: body
          required: true
          description: Transaction update payload
          schema:
            $ref: "#/definitions/TransactionInformations"
      produces:
        - application/json
      responses:
        "200":
          description: Information of transaction updated successully
          schema:
            $ref: "#/definitions/TransactionInformations"
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Delete transaction information
      description: API for delete a transaction information
      parameters:
        - name: Authorization
          in: header
          description: Attach Bearer JWT token
          required: true
          type: string
        - name: transactionId
          in: path
          description: ID of transaction to update
          required: true
          type: string
        - in: body
          name: body
          required: true
          description: Delete transaction payload
          schema:
            $ref: "#/definitions/DeleteTransaction"
      produces:
        - application/json
      responses:
        "200":
          description: Information deleted successully
          schema:
            $ref: "#/definitions/TransactionInformations"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  AccountTransactions:
    properties:
      id:
        type: string
        description: Id of account
      ownerId:
        type: string
        description: Owner of account
      amount:
        type: number
        description: Current amount of account
      currency:
        type: string
        description: Currency of account
      transactions:
          type: array
          items:
            $ref: '#/definitions/TransactionObject'
  TransactionObject:
    properties:
      id:
        type: string
        description: Account identifier
      description:
        type: string
        description: Name of transaction (ex John Bakery, NetFlix...)
      category:
        type: string
        description: Category of transaction (ex Food, Health, Work...)
      amount:
        type: number
        description: Amount
      recipient:
        type: string
        description: Recipient of the transaction
  TransactionInformations:
    properties:
      description:
        type: string
        description: Description of transaction (ex Johnson Bakery meal)
      category:
        type: string
        description: Category of transaction
  DeleteTransaction:
    properties:
      description:
        type: boolean
        description: if true, empty the description
      category:
        type: boolean
        description: if true, empty the category
